image: ghcr.io/strongishllama/terraform-cdk-constructs-gitpod:main

vscode:
  extensions:
    - esbenp.prettier-vscode
    - exiasr.hadolint
    - golang.go
    - hashicorp.hcl
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - redhat.vscode-yaml
    - streetsidesoftware.code-spell-checker
    - timonwong.shellcheck
    - waderyan.gitblame
