export enum RecordSetType {
  A = "A",
  AAAA = "AAAA",
  CAA = "CAA",
  CNAME = "CNAME",
  DNSKEY = "DNSKEY",
  DS = "DS",
  HTTPS = "HTTPS",
  IPSECKEY = "IPSECKEY",
  MX = "MX",
  NAPTR = "NAPTR",
  NS = "NS",
  PTR = "PTR",
  SPF = "SPF",
  SRV = "SRV",
  SSHFP = "SSHFP",
  SVCB = "SVCB",
  TLSA = "TLSA",
  TXT = "TXT",
}
