name: Publish
on:
  push:
    branches:
      - main
    paths:
      - packages/**
      - "!packages/.prettierrc"
      - .github/workflows/publish.yaml
  pull_request:
    branches:
      - main
    paths:
      - packages/**
      - "!.prettierrc"
      - "!packages/.prettierrc"
      - .github/workflows/publish.yaml
permissions:
  contents: write
jobs:
  lint:
    name: Lint
    uses: strongishllama/github-actions/.github/workflows/npm-lint.yaml@main
    with:
      path: packages/
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies
        run: npm run lerna -- exec "npm install"
        working-directory: .
      - name: Build
        run: npm run lerna -- run build
  bump-tag:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs:
      - lint
      - test
    name: Bump Tag
    uses: strongishllama/github-actions/.github/workflows/bump-tag.yaml@main
  release:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs:
      - bump-tag
    name: Release
    uses: strongishllama/github-actions/.github/workflows/github-release.yaml@main
    with:
      tag: ${{ needs.bump-tag.outputs.bumped-tag }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs:
      - bump-tag
      - release
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org
          scope: ${{ inputs.scope }}
      - name: Updated Package Version
        run: |
          npm run lerna -- version ${{ needs.bump-tag.outputs.bumped-tag }} --no-git-tag-version --no-push --yes
        working-directory: .
      - name: Install Dependencies
        run: npm run lerna -- exec "npm install"
        working-directory: .
      - name: Build
        run: npm run lerna -- run build
        working-directory: .
      - name: Publish
        run: npm run lerna -- publish ${{ needs.bump-tag.outputs.bumped-tag }} --force-publish=* --no-git-tag-version --no-push --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
        working-directory: .
